// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxjbKs7kGIIgdoCItA_NP2n3ZmsLaFXtw',
    appId: '1:756506665902:web:25aa8fc452c70220581e3f',
    messagingSenderId: '756506665902',
    projectId: 'disastermanagement-90b30',
    authDomain: 'disastermanagement-90b30.firebaseapp.com',
    storageBucket: 'disastermanagement-90b30.firebasestorage.app',
    measurementId: 'G-NW93BF6N0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBvf-dK5MPHeP5NXebkmzhVF9P9nD9I2k',
    appId: '1:756506665902:android:bd4031f9f3e9ca1f581e3f',
    messagingSenderId: '756506665902',
    projectId: 'disastermanagement-90b30',
    storageBucket: 'disastermanagement-90b30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAULhp8D5satehwgoxkgumikFsHlvQQDb0',
    appId: '1:756506665902:ios:e47d8e50cde1d248581e3f',
    messagingSenderId: '756506665902',
    projectId: 'disastermanagement-90b30',
    storageBucket: 'disastermanagement-90b30.firebasestorage.app',
    iosBundleId: 'com.example.dm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAULhp8D5satehwgoxkgumikFsHlvQQDb0',
    appId: '1:756506665902:ios:e47d8e50cde1d248581e3f',
    messagingSenderId: '756506665902',
    projectId: 'disastermanagement-90b30',
    storageBucket: 'disastermanagement-90b30.firebasestorage.app',
    iosBundleId: 'com.example.dm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxjbKs7kGIIgdoCItA_NP2n3ZmsLaFXtw',
    appId: '1:756506665902:web:5d883f1a8df35cbb581e3f',
    messagingSenderId: '756506665902',
    projectId: 'disastermanagement-90b30',
    authDomain: 'disastermanagement-90b30.firebaseapp.com',
    storageBucket: 'disastermanagement-90b30.firebasestorage.app',
    measurementId: 'G-LL7LPH26WF',
  );
}
